# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013
  project: Générateur et visionneuse de documentation Sphinx Python
  version: 1.1
  release: 1.1.1-dev
  latex_documents:
  - - Index
    - sphinx.tex
    - Générateur et visionneuse de documentation Sphinx Python
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
