# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013-2014
  project: Sphinx Python Documentation Generator and Viewer
  version: 1.3
  release: 1.3.0
  latex_documents:
  - - Index
    - sphinx.tex
    - Sphinx Python Documentation Generator and Viewer
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    restdoc:
    - http://docs.typo3.org/typo3cms/extensions/restdoc/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
  - sphinxcontrib.googlechart
  - sphinxcontrib.googlemaps
  - sphinxcontrib.slide
  - sphinxcontrib.youtube
...
