# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013-2017
  project: Sphinx Python Documentation Generator and Viewer
  version: 2.5
  release: 2.5.0-dev
  latex_documents:
  - - Index
    - sphinx.tex
    - Sphinx Python Documentation Generator and Viewer
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  latex_use_parts: True
  latex_show_pagerefs: True
  intersphinx_mapping:
    restdoc:
    - https://docs.typo3.org/typo3cms/extensions/restdoc/
    - null
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3cmsapi:
    - https://typo3.org/api/typo3cms/
    - null
  extlinks:
    ter:
    - https://typo3.org/extensions/repository/view/%s
    - 'TYPO3 extension '
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
  - sphinx.ext.extlinks
  - sphinxcontrib.googlechart
  - sphinxcontrib.googlemaps
  - sphinxcontrib.slide
  - sphinxcontrib.youtube
...
